version: '3.8'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - $PWD/:/usr/share/nginx/html
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
